files_origin: '/Users/aperret/Repositories/cosma-but-infocom/fiches'
export_target: '/Users/aperret/Repositories/cosma-but-infocom/'
history: false
focus_max: 2
record_types:
  undefined: "#858585"
  ressource: "#009e7e"
  SAE: "#555555"
  parcours: "#cc79a7"
  UE: "#eca843"
  semestre: "#56b4e9"
  année: "#ce01e9"
link_types:
  undefined:
    stroke: simple
    color: '#e1e1e1'
graph_background_color: '#ffffff'
graph_highlight_color: '#e58080'
graph_highlight_on_hover: true
graph_text_size: 5
graph_arrows: true
attraction_force: 70
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
title: 'BUT Info-com'
author: 'Clément Borel & Arthur Perret'
description: ''
keywords: []
link_symbol: '→'
csl: ''
bibliography: ''
csl_locale: ''
css_custom: ''
devtools: false
lang: fr
